// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Sistema.Migrations.SqliteMigrations
{
    [DbContext(typeof(NOMINAContext))]
    partial class NOMINAContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("NOMINA", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("beneficio")
                        .HasColumnType("REAL");

                    b.Property<double>("bonos")
                        .HasColumnType("REAL");

                    b.Property<double>("impuestos")
                        .HasColumnType("REAL");

                    b.Property<double>("salarioFinal")
                        .HasColumnType("REAL");

                    b.Property<double>("sueldo")
                        .HasColumnType("REAL");

                    b.HasKey("id");

                    b.ToTable("NOMINA");
                });
#pragma warning restore 612, 618
        }
    }
}
